version: '3.5'

services:
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
  pangalink:
    image: 'laurielias/pangalink'
    container_name: 'pangalink'
    build: .
    ports:
      - '8001:3480'
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
    volumes:
      - ./data:/home/pangalink/data
      - ./config:/home/pangalink/config